# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Test__Directional_Covariate <- function(x, y) {
    .Call(`_movecon_Test__Directional_Covariate`, x, y)
}

build_statespace <- function(eastings, northings, covariates, linear_constraint) {
    .Call(`_movecon_build_statespace`, eastings, northings, covariates, linear_constraint)
}

extract_statespace_location <- function(statespace, easting_ind, northing_ind) {
    .Call(`_movecon_extract_statespace_location`, statespace, easting_ind, northing_ind)
}

extract_statespace_state <- function(statespace, last_movement_direction, easting_ind, northing_ind) {
    .Call(`_movecon_extract_statespace_state`, statespace, last_movement_direction, easting_ind, northing_ind)
}

build_statespace_search <- function(statespace) {
    .Call(`_movecon_build_statespace_search`, statespace)
}

nearest_location_in_domain <- function(statespace_search, easting, northing) {
    .Call(`_movecon_nearest_location_in_domain`, statespace_search, easting, northing)
}

states_at_nearest_location_in_domain <- function(statespace_search, easting, northing) {
    .Call(`_movecon_states_at_nearest_location_in_domain`, statespace_search, easting, northing)
}

Test__Particle_Steps <- function(statespace, last_movement_direction, easting_ind, northing_ind, directional_persistence, beta, delta, nsteps) {
    .Call(`_movecon_Test__Particle_Steps`, statespace, last_movement_direction, easting_ind, northing_ind, directional_persistence, beta, delta, nsteps)
}

Test__Particle_Filter_Likelihood <- function(eastings, northings, semi_majors, semi_minors, orientations, statespace, last_movement_direction, easting_ind, northing_ind, nparticles, directional_persistence, beta, delta) {
    .Call(`_movecon_Test__Particle_Filter_Likelihood`, eastings, northings, semi_majors, semi_minors, orientations, statespace, last_movement_direction, easting_ind, northing_ind, nparticles, directional_persistence, beta, delta)
}

Test__Directional_Transition_Probabilities <- function(statespace, last_movement_direction, easting_ind, northing_ind, directional_persistence) {
    .Call(`_movecon_Test__Directional_Transition_Probabilities`, statespace, last_movement_direction, easting_ind, northing_ind, directional_persistence)
}

Test__Location_Based_Movement_Transition_Rate <- function(statespace, last_movement_direction, easting_ind, northing_ind, beta) {
    .Call(`_movecon_Test__Location_Based_Movement_Transition_Rate`, statespace, last_movement_direction, easting_ind, northing_ind, beta)
}

log_sum <- function(x) {
    .Call(`_movecon_log_sum`, x)
}

log_cumsum <- function(x) {
    .Call(`_movecon_log_cumsum`, x)
}

