# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_statespace <- function(eastings, northings, covariates) {
    .Call(`_movecon_build_statespace`, eastings, northings, covariates)
}

extract_statespace_location <- function(statespace, easting_ind, northing_ind) {
    .Call(`_movecon_extract_statespace_location`, statespace, easting_ind, northing_ind)
}

extract_statespace_state <- function(statespace, last_movement_direction, easting_ind, northing_ind) {
    .Call(`_movecon_extract_statespace_state`, statespace, last_movement_direction, easting_ind, northing_ind)
}

